### PR TITLE
remove from repository/ignore Emacs and binary files

### PR DESCRIPTION
**Pull request by Cynede**

### CODE REVIEW

**Comment by Chobbes** [comment]
:+1: 

One thing we might want to consider is keeping an example idrOS.bin around so people who don't have the cross compiler set up can easily fire qemu up to see it work. Maybe we should have an examples directory? This is a bit unorthodox, so maybe we should just get rid of the binary. I know the first thing I'm going to try is running it under qemu, though :).

You beat me to the first pull request :P.

**Comment by Cynede** [comment]
@Chobbes sadly github has removed way to distribute binaries so I think the right way will be 3d-party hosting for them and just link in readme.

Also I missed iso file, not sure I wanted to keep it or not

**Comment by stepcut** [comment]
I'd like to keep the .iso and .bin files around for now to make it easy to try it out with out having to actually build it yourself. I am not sure what you mean by github having removed a way to distribute binaries.  If you go here:

https://github.com/stepcut/idrOS/blob/master/idrOS.bin

And click on `Raw` you can download the binary and run it in qemu..

**Comment by Cynede** [comment]
@stepcut I've moved back `.bin` file and made rebase on it.
Early github has way just to distribute binries, not directly from repository, here is it: https://github.com/blog/1302-goodbye-uploads
And here is what they do suggest: https://help.github.com/articles/distributing-large-binaries , a lot of people use sourceforge: http://sourceforge.net/publish/?source=github

**Comment by stepcut** [comment]
Thanks. Obviously, github is not a great long term solution for distributing binaries. But the .bin and .iso files are so small at the moment that simplicity wins.

**Comment by lee-b** [comment]
> One thing we might want to consider is keeping an example idrOS.bin around so people who don't have the cross compiler set up can easily fire qemu up to see it work.

This would be better done as a releases upload, I think.

**Pull request merged**
